#!/usr/bin/python3
import os
import subprocess
import time
file_list = [
    "vbmeta_system.img",
    "vbmeta.img",
    "devcfg.img",
    "xbl_config.img",
    "qupfw.img",
    "featenabler.img",
    "uefisecapp.img",
    "rpm.img",
    "abl.img",
    "keymaster.img",
    "hyp.img",
    "bluetooth.img",
    "countrycode.img",
    "imagefv.img",
    "tz.img",
    "xbl.img",
    "dtbo.img",
    "init_boot.img",
    "dsp.img",
    "vendor_boot.img",
    "boot.img",
    "modem.img",
    "cust.img"
]
def system(cmd):
    return subprocess.check_output(cmd,shell=True)
files = subprocess.check_output("ls | grep '.img'",shell=True).split()
file_list  = files
file_sizes = [(file.decode(), os.path.getsize(file)) for file in file_list if os.path.exists(file)]
file_sizes.sort(key=lambda x: x[1])
# for file,size in file_sizes:
#     print(f"{file} {size}")
blacklist = ["super.img"]
for file,size in file_sizes:
    if file in blacklist:
        continue
    system(f"fastboot flash {file[:-4]} {file}")
# # os.system(f"fastboot flash super super.img")
